create/urls.py
from django.conf.urls import url
from . import views

app_name = 'create'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'result/$', views.result, name="result"),
]

reg/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'reg'
urlpatterns = [
    url(r'^$', views.RegisterForm.as_view(), name="reg"),
    url(r'^profile/', views.update_profile, name='profile'),
    url(r'^login/', views.AuthForm.as_view(), name='login'),
    url(r'^logout/', views.LogoutView.as_view(), name='logout'),
    url(r'^check/', views.check, name='check'),
]

startsurvey/urls.py
from django.conf.urls import url
from . import views

app_name = 'startsurvey'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    # url(r'^(?P<test_id>[0-9])/$', views.vote, name="vote"),
    url(r'^(?P<test_id>[0-9])/$', views.start, name="start"),
    # url(r'^(?P<test_id>[0-9])/result/$', views.result, name="result"),
]

survey/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('mainpage.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('mainpage.urls')),
    url(r'^create/', include('create.urls')),
    url(r'^start/', include('startsurvey.urls')),
    url(r'^reg/', include('reg.urls')),
    # url(r'^login', )
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

{#    <link rel="stylesheet" href="{% static 'css/main.css'%}">#}
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300" type="text/css">
    {% block title %}

    {% endblock %}
</head>
<body>
    {% block head %}
        {% block staticbuttons %}
        <dev class="headbutton staticbuttons">
            <a href="{% url 'create:index' %}">Создать тест</a>
        </dev>
        <dev class="headbutton staticbuttons">
            <a href="{% url 'startsurvey:index' %}">Выбрать тест</a>
        </dev>
        <dev class="headbutton staticbuttons">
        </dev>
        {% endblock %}
        {% block dynamicbuttons %}
            <dev class="headbutton dynamicbuttons">

            </dev>
        {% endblock %}
    {% endblock%}

    {% autoescape on %}
    {% block body %}
    {% endblock%}
    {% endautoescape %}
</body>
</html>